### ISSUE TITLE
Should redirect to URL collection if all alt URLs fail

### ISSUE THREAD

**Issue by greatfire-martin** [Behemouth/website-mirror-by-proxy#7]
URL collections being GitHub and BitBucket, as defined in the conf file. If all domains fail, the user should be redirected to one of them. The site should attempt to decide which one works before redirecting, so that for example if BitBucket has been blocked the user isn't redirected there.

**Comment by Behemouth** [comment]
The current implementation is same as it used to be,except add a confirm message to ask if user want to navigate to URL Collection page. Detect which one works before redirecting is not possible to realise,because we can't send direct request to Github or BitBucket because of Access-Control. It's unable to  distinguish between Access error and connection reset error by XMLHttpRequest or iframe.

**Comment by greatfire-martin** [comment]
I think the Access-Control problem can be resolved by loading an image from the respective site, eg /favicon.ico, and then using the onLoad event, no?

**Comment by Behemouth** [comment]
Good idea,I forgot this approach at all.
